export const T = {
  bg: '#111',
  surface: '#181818',
  elevated: '#222',
  border: '#2a2a2a',
  text: '#999',
  textBright: '#eee',
  accent: '#fff',
  accentColor: '#0af',
  gold: '#fd4',
  danger: '#f44',
  success: '#4f4',
  nodeColors: { scene: '#4a9eff', choice: '#ff9f43', condition: '#a55eea' },
  font: "'Inter', 'Helvetica Neue', Helvetica, system-ui, sans-serif",
  mono: "'JetBrains Mono', 'Fira Code', monospace",
  fontSize: { xs: 11, sm: 13, md: 15, lg: 20, xl: 32 },
  sp: (n) => n * 4,
  radius: 0,
}
