export const T = {
  bg: '#0e0e0e',
  surface: '#161616',
  elevated: '#1e1e1e',
  border: '#2c2c2c',
  text: '#888',
  textBright: '#ddd',
  accent: '#fff',
  accentColor: '#0af',
  gold: '#fd4',
  danger: '#f44',
  success: '#4f4',
  nodeColors: { scene: '#4a9eff', choice: '#ff9f43', condition: '#a55eea' },
  font: "'Inter', 'Helvetica Neue', Helvetica, system-ui, sans-serif",
  mono: "'JetBrains Mono', 'Fira Code', monospace",
  fontSize: { xs: 11, sm: 13, md: 15, lg: 20, xl: 32 },
  sp: (n) => n * 4,
  radius: 6,
  shadow: '0 2px 8px rgba(0,0,0,0.4)',
}
