import json


def generate_maps_js(data):
    """Generate maps.js from _maps.json data (dict of named maps)."""
    lines = [
        "// maps.js — ForkArcade map definitions",
        "// Generated from _maps.json by apply_data_patch tool",
        "",
        "if (!window.FA) window.FA = {};",
        "if (!FA.assets) FA.assets = { spriteDefs: null, spritesheet: null, sheetCols: 16, mapDefs: null };",
        "",
        "FA.assets.mapDefs = " + json.dumps(data, indent=2),
        "",
        "function getMap(name) {",
        "  return FA.assets.mapDefs[name] || null",
        "}",
        "",
        "function getMapGrid(name) {",
        "  var m = FA.assets.mapDefs[name]",
        "  if (!m || !m.grid) return null",
        "  return m.grid.map(function(row) {",
        "    return row.split('').map(Number)",
        "  })",
        "}",
        "",
        "function getMapObjects(name) {",
        "  return (FA.assets.mapDefs[name] || {}).objects || []",
        "}",
        "",
        "function getMapZones(name) {",
        "  var m = FA.assets.mapDefs[name]",
        "  if (!m || !m.zones) return null",
        "  return m.zones.map(function(row) {",
        "    return row.split('')",
        "  })",
        "}",
        "",
        "function getMapFrameGrid(name) {",
        "  var m = FA.assets.mapDefs[name]",
        "  if (!m || !m.frameGrid) return null",
        "  var C = '0123456789abcdefghij'",
        "  return m.frameGrid.map(function(row) {",
        "    return row.split('').map(function(c) { return C.indexOf(c) })",
        "  })",
        "}",
        "",
    ]
    return "\n".join(lines)
